version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/p2p_messaging.log
    mode: a

loggers:
  PeerNode:
    level: DEBUG
    handlers: [console, file]
  
  ConnectionManager:
    level: DEBUG
    handlers: [console, file]
  
  MessageQueue:
    level: INFO
    handlers: [console, file]

root:
  level: INFO
  handlers: [console, file]